SELECT TOP 100
	A.NIP_BARU, E.SATUAN_KERJA AS SATKER1, D.SATUAN_KERJA AS SATKER2, A.SATUAN_KERJA AS SATKER3, E.KODE_SATUAN_KERJA AS KODE_SATKER1, A.MUTASI
FROM vwDATA_PEGAWAI A 
LEFT JOIN TM_SATUAN_KERJA d ON d.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,6)+'00000000' 
LEFT JOIN TM_SATUAN_KERJA e ON e.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,4)+'0000000000'
WHERE LEN(A.NIP_BARU)>1  
    --AND (NO_SK_GOL='' OR NO_SK_GOL IS NULL OR NO_SK_JAB='' OR NO_SK_JAB IS NULL OR NO_SK_GOL_KGB='' OR NO_SK_GOL_KGB IS NULL OR NO_HP='' OR NO_HP IS NULL OR EMAIL='' OR EMAIL IS NULL OR H.TAHUN='' OR H.TAHUN IS NULL) 
    --AND A.KODE_SATUAN_KERJA LIKE '0103%'
order by a.KODE_SATUAN_KERJA
