SELECT 
    A.NIP_BARU, A.NAMA_LENGKAP, CONVERT(VARCHAR, A.TMT_PENSIUN,23) AS TMT_PENSIUN, B.ALMARI
FROM vwDATA_PEGAWAI A 
LEFT JOIN TD_TAKAH B ON B.NIP = A.NIP 
WHERE A.KODE_MUTASI IN ('3','12') AND ALMARI IS NOT NULL
ORDER BY A.TMT_PENSIUN 
