SELECT --TOP 100 
	A.NIP_BARU, A.NAMA_LENGKAP, CONVERT(VARCHAR, A.TMT_PENSIUN,23) AS TMT_PENSIUN, YEAR(a.TMT_PENSIUN) as THN_PENSIUN, 
	f.LEVEL_JABATAN, a.JENIS_KELAMIN, a.AGAMA, a.JENJANG_PENDIDIKAN, a.GOL_RUANG,
	e1.KODE_SATUAN_KERJA AS KODE_SATKER0, e1.SATUAN_KERJA as SATKER0, E.SATUAN_KERJA AS SATKER1, D.SATUAN_KERJA AS SATKER2, A.SATUAN_KERJA, 
    MUTASI
FROM vwDATA_PEGAWAI A 
LEFT JOIN TM_SATUAN_KERJA d ON d.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,6)+'00000000' 
LEFT JOIN TM_SATUAN_KERJA e ON e.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,4)+'0000000000'
LEFT JOIN TM_SATUAN_KERJA e1 ON e1.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,2)+'000000000000'
LEFT JOIN TM_LEVEL_JABATAN f on f.KODE_LEVEL_JABATAN = a.KODE_LEVEL_JABATAN
WHERE 
    KODE_MUTASI IN ('1','2','3','4','12') AND 
    YEAR(TMT_PENSIUN) IN ('2024') AND
    YEAR(A.TIME_UPDATE) = '2024'
order by a.KODE_SATUAN_KERJA, YEAR(TMT_PENSIUN)

