SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP, 
    RTRIM(REPLACE(A.TEMPAT_LAHIR,',','')) AS TEMPAT_LAHIR, CAST(A.TANGGAL_LAHIR AS DATE) AS TANGGAL_LAHIR, DATEDIFF(YEAR, A.TANGGAL_LAHIR, GETDATE()) AS USIA, 
    CAST(A.MASUK_PEGAWAI AS date) AS MASUK_PEGAWAI, 
    CAST(
        CAST(CASE WHEN MONTH(A.TANGGAL_LAHIR) = 12 THEN year(A.TANGGAL_LAHIR) + IA.USIA_PENSIUN + 1 ELSE year(A.TANGGAL_LAHIR) + IA.USIA_PENSIUN END AS varchar(4)) + '/' + 
        CAST(CASE WHEN MONTH(A.TANGGAL_LAHIR) = 12 THEN '1' ELSE MONTH(A.TANGGAL_LAHIR) + 1 END AS varchar(2)) + '/1' AS date) AS TMT_PENSIUN,
    IIF(A.JENIS_KELAMIN=0,'Perempuan','Laki-Laki') AS JENIS_KELAMIN, B.AGAMA, C.STATUS_KAWIN, 
    D.STATUS_PEGAWAI,   
    GA.JENJANG_PENDIDIKAN, HA.PANGKAT, 
	CASE WHEN A.KODE_STATUS_PEGAWAI <> 3 THEN HA.GOL_RUANG ELSE HA.GOL_PPPK END GOL_RUANG, 
    COALESCE (CASE WHEN (datediff(mm, H.TMT_SK, GETDATE()) % 12 + h.mk_bulan) > 11 
                    THEN datediff(mm, H.TMT_SK, GETDATE()) / 12 + h.mk_tahun + 1 
                    ELSE datediff(mm, H.TMT_SK, GETDATE()) / 12 + h.mk_tahun END, 0) AS MK_TAHUN, 
    COALESCE (CASE WHEN (datediff(mm, H.TMT_SK, GETDATE()) % 12 + h.mk_bulan) > 11 
                    THEN datediff(mm, H.TMT_SK, GETDATE()) % 12 + h.mk_bulan - 12 
                    ELSE datediff(mm, H.TMT_SK, GETDATE()) % 12 + h.mk_bulan END, 0) AS MK_BULAN,
    H.NO_SK AS NO_SK_PANGKAT, CAST(H.TGL_SK AS DATE) AS TGL_SK_PANGKAT, CAST(H.TMT_SK AS DATE) AS TMT_SK_PANGKAT, 
    IA.JABATAN, I.NO_SK AS NO_SK_JAB, CAST(I.TGL_SK AS DATE) AS TGL_SK_JAB, CAST(I.TMT_SK AS DATE) AS TMT_SK_JAB, IA.USIA_PENSIUN,  
    JB.LEVEL_JABATAN,
    CASE 
        WHEN JB.KODE_TIPE_JABATAN=0 THEN 'Struktural'
        WHEN JB.KODE_TIPE_JABATAN=1 THEN 'Pelaksana'
        WHEN JB.KODE_TIPE_JABATAN=2 THEN 'Fungsional'
        ELSE JB.KODE_TIPE_JABATAN
    END AS TIPE_JABATAN, IK.GRADE,
    ICC.GRUP_SATUAN_KERJA,
    IIF(LEN(DL.NPWP)>1,'ada','') AS NPWP, IIF(LEN(DL.KTP)>1,'ada','') AS KTP,
    DA.JML_ANAK, DA.JML_ANAK_TTG,
    DSI.JML_PASANGAN, DSI.PASANGAN_TTG,
    IIF(DSR.SERTIFIKASI>0,'Sertifikasi','') AS SERTIFIKASI,
    S1.KODE_SATUAN_KERJA AS KODE_SATKER1, S1.SATUAN_KERJA AS SATKER1, S2.KODE_SATUAN_KERJA AS KODE_SATKER2, S2.SATUAN_KERJA AS SATKER2,
    S3.KODE_SATUAN_KERJA AS KODE_SATKER3, S3.SATUAN_KERJA AS SATKER3, S4.KODE_SATUAN_KERJA AS KODE_SATKER4, S4.SATUAN_KERJA AS SATKER4,
    I.KODE_SATUAN_KERJA, 
    CASE LEFT(IC.SATUAN_KERJA, 8) WHEN 'Kelompok' THEN(SELECT SATUAN_KERJA FROM TM_SATUAN_KERJA WHERE KODE_SATUAN_KERJA = IC.KODE_ATASAN) ELSE IC.SATUAN_KERJA END AS SATUAN_KERJA
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TM_AGAMA AS B ON A.KODE_AGAMA = B.KODE_AGAMA LEFT OUTER JOIN
    dbo.TM_STATUS_KAWIN AS C ON A.KODE_STATUS_KAWIN = C.KODE_STATUS_KAWIN LEFT OUTER JOIN
    dbo.TM_STATUS_PEGAWAI AS D ON A.KODE_STATUS_PEGAWAI = D.KODE_STATUS_PEGAWAI LEFT OUTER JOIN
    dbo.TM_JENIS_PEGAWAI AS E ON A.KODE_JENIS_PEGAWAI = E.KODE_JENIS_PEGAWAI LEFT OUTER JOIN
    dbo.TM_MUTASI AS F ON A.KODE_MUTASI = F.KODE_MUTASI LEFT OUTER JOIN
    dbo.TR_PENDIDIKAN AS G ON A.NIP = G.NIP AND A.NO_URUT_PENDIDIKAN = G.NO_URUT LEFT OUTER JOIN
    dbo.TM_JENJANG_PENDIDIKAN AS GA ON G.KODE_JENJANG_PENDIDIKAN = GA.KODE_JENJANG_PENDIDIKAN LEFT OUTER JOIN
    (SELECT        
        NIP, NO_URUT, KODE_PANGKAT, NO_SK, TGL_SK, TMT_SK, MK_TAHUN, MK_BULAN, KETERANGAN, 
        USER_ADD, TIME_ADD, USER_UPDATE, TIME_UPDATE, JENIS_SK, PENANDATANGAN, DASAR_HUKUM, GAJI_POKOK
    FROM            
        dbo.TR_PANGKAT) AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TM_PANGKAT AS HA ON H.KODE_PANGKAT = HA.KODE_PANGKAT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_JABATAN AS IA ON I.KODE_JABATAN = IA.KODE_JABATAN LEFT OUTER JOIN
    dbo.TM_LEVEL_JABATAN AS JB ON IA.KODE_LEVEL_JABATAN = JB.KODE_LEVEL_JABATAN LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS IC ON I.KODE_SATUAN_KERJA = IC.KODE_SATUAN_KERJA LEFT OUTER JOIN
    dbo.TM_GRUP_SATUAN_KERJA AS ICC ON IC.KODE_GRUP_SATUAN_KERJA=ICC.KODE_GRUP_SATUAN_KERJA LEFT OUTER JOIN
    dbo.TM_JABATAN AS IE ON I.KODE_JABATAN_2 = IE.KODE_JABATAN LEFT OUTER JOIN
    dbo.TM_JABATAN_TUKIN AS IK ON I.KODE_JABATAN = IK.KODE_JABATAN LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS IG ON I.KODE_SATUAN_KERJA_2 = IG.KODE_SATUAN_KERJA LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' LEFT OUTER JOIN
    dbo.TM_PANGKAT AS IH ON I.KODE_PANGKAT = IH.KODE_PANGKAT LEFT OUTER JOIN
    dbo.TD_LAIN AS DL ON A.NIP = DL.NIP LEFT OUTER JOIN
    (
        SELECT NIP, COUNT(NO_URUT) AS JML_ANAK, 
        SUM(CAST(ISNULL(TERTANGGUNG,0) AS INT)) AS JML_ANAK_TTG 
        FROM TD_ANAK
        GROUP BY NIP
    ) AS DA ON A.NIP = DA.NIP LEFT OUTER JOIN
    (
        SELECT NIP, COUNT(NO_URUT) AS JML_PASANGAN, SUM(CAST(ISNULL(TERTANGGUNG,0) AS INT)) AS PASANGAN_TTG 
        FROM TD_SUAMI_ISTRI
        GROUP BY NIP
    ) AS DSI ON A.NIP = DSI.NIP LEFT OUTER JOIN
    (
        SELECT NIP, COUNT(NO_URUT) AS SERTIFIKASI 
        FROM TR_SERTIFIKASI
        GROUP BY NIP
    ) AS DSR ON A.NIP = DSR.NIP LEFT OUTER JOIN
    dbo.TR_KGB AS J ON A.NIP = J.NIP AND A.NO_URUT_KGB = J.NO_URUT LEFT OUTER JOIN
    (SELECT        
        NIP, MAX(KODE_PANGKAT) / 10 AS max_data, MIN(KODE_PANGKAT) / 10 AS min_data
    FROM            
        dbo.TR_PANGKAT AS TR_PANGKAT_1
    GROUP BY NIP) AS K ON A.NIP = K.NIP LEFT OUTER JOIN
    dbo.fnPengurangMK() AS l ON K.min_data = l.mk_awal AND K.max_data = l.mk_akhir 
WHERE A.KODE_MUTASI=1
ORDER BY IC.KODE_SATUAN_KERJA