SELECT 
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN A.TANGGAL_LAHIR IS NULL THEN 'Tanggal Lahir Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (A.TANGGAL_LAHIR IS NULL)  
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN LEN(A.TEMPAT_LAHIR)<2 THEN 'Tempat Lahir Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND LEN(A.TEMPAT_LAHIR)<2 
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN A.MASUK_PEGAWAI IS NULL THEN 'Masuk Pegawai Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND A.MASUK_PEGAWAI IS NULL 
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN A.KODE_AGAMA IS NULL OR A.KODE_AGAMA=0 THEN 'Agama Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_PANGKAT AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (A.KODE_AGAMA IS NULL OR A.KODE_AGAMA=0)
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN A.KODE_STATUS_PEGAWAI IS NULL OR A.KODE_STATUS_PEGAWAI=0 THEN 'Status Pegawai Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_PANGKAT AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (A.KODE_STATUS_PEGAWAI IS NULL OR A.KODE_STATUS_PEGAWAI=0)
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN H.NO_SK IS NULL OR LEN(H.NO_SK)<2 THEN 'No SK Pangkat/Gol Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_PANGKAT AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (H.NO_SK IS NULL OR LEN(H.NO_SK)<2) 
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN H.MK_TAHUN IS NULL OR H.MK_TAHUN>40 OR (H.NO_URUT>1 AND H.MK_TAHUN=0) THEN 'Masa Kerja Pangkat/Gol Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_PANGKAT AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (H.MK_TAHUN IS NULL OR H.MK_TAHUN>40 OR (H.NO_URUT>1 AND H.MK_TAHUN=0)) 
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN YEAR(H.TGL_SK)=1900 OR YEAR(H.TMT_SK)=1900 THEN 'Tgl/TMT Pangkat/Gol Tidak Sesuai'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_PANGKAT AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (YEAR(H.TGL_SK)=1900 OR YEAR(H.TMT_SK)=1900) 
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN I.NO_SK IS NULL OR LEN(I.NO_SK)<2 THEN 'No SK Jabatan Kosong'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_PANGKAT AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (I.NO_SK IS NULL OR LEN(I.NO_SK)<2) 
UNION
SELECT --TOP 100
    A.NIP_BARU,  
    LTRIM(COALESCE (A.GDN1, '') + ' ') + LTRIM(COALESCE(RTRIM(A.GDN2), '') + ' ') + LTRIM(COALESCE (RTRIM(REPLACE(A.NAMA,',','')), '')) + LTRIM(COALESCE (CASE WHEN LEN(A.GBN)>1 THEN + ', ' + A.GBN END, '')) AS NAMA_LENGKAP,
    CASE 
        WHEN YEAR(I.TGL_SK)=1900 OR YEAR(I.TMT_SK)=1900 THEN 'Tgl/TMT Jabatan Tidak Sesuai'
    END ANOMALI,
    S1.SATUAN_KERJA AS SATKER1, S2.SATUAN_KERJA AS SATKER2,
    S3.SATUAN_KERJA AS SATKER3, S4.SATUAN_KERJA AS SATKER4
FROM            
    dbo.TM_PEGAWAI AS A LEFT OUTER JOIN
    dbo.TR_PANGKAT AS H ON A.NIP = H.NIP AND A.NO_URUT_PANGKAT = H.NO_URUT LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    dbo.TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(I.KODE_SATUAN_KERJA,8)+'000000' 
WHERE A.KODE_MUTASI=1  
    AND (YEAR(I.TGL_SK)=1900 OR YEAR(I.TMT_SK)=1900) 