SELECT --TOP 100
    A.NIP_BARU, A.NAMA_LENGKAP, IIF(A.JENIS_KELAMIN=0,'Perempuan','Laki-Laki') AS JENIS_KELAMIN, A.AGAMA, A.STATUS_KAWIN, A.STATUS_PEGAWAI,
	A.JENJANG_PENDIDIKAN, A.PANGKAT, A.GOL_RUANG, A.NO_SK_GOL, A.TGL_SK_GOL, A.TMT_SK_GOL, A.MK_TAHUN, A.MK_BULAN,
	A.JABATAN, f.LEVEL_JABATAN, A.NO_SK_JAB, A.TGL_SK_JAB, A.TMT_SK_JAB, A.GOL_RUANG_JABATAN, A.KODE_TIPE_JABATAN,
	A.NO_SK_GOL_KGB, A.TMT_SK_GOL_KGB, A.TMT_SK_GOL_KGB, A.MK_TAHUN_KGB, A.MK_BULAN_KGB, A.GOL_RUANG_KGB,
	A.USIA_PENSIUN, A.TMT_PENSIUN, G.NO_HP, G.EMAIL, H.TAHUN AS SKP2022, a.KODE_SATUAN_KERJA,
	E.KODE_SATUAN_KERJA AS KODE_SATKER1, E.SATUAN_KERJA AS SATKER1, D.SATUAN_KERJA AS SATKER2, A.SATUAN_KERJA, D.PROGRAM,
    CASE 
        WHEN F.KODE_TIPE_JABATAN=0 THEN 'Struktural'
        WHEN F.KODE_TIPE_JABATAN=1 THEN 'Pelaksana'
        WHEN F.KODE_TIPE_JABATAN=2 THEN 'Fungsional'
        ELSE F.KODE_TIPE_JABATAN
    END AS TIPE_JABATAN, J.grade as KELAS_JABATAN
FROM vwDATA_PEGAWAI A 
LEFT JOIN TM_SATUAN_KERJA d ON d.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,6)+'00000000' 
LEFT JOIN TM_SATUAN_KERJA e ON e.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,4)+'0000000000'
LEFT JOIN TM_LEVEL_JABATAN f on f.KODE_LEVEL_JABATAN = a.KODE_LEVEL_JABATAN
LEFT JOIN TD_ALAMAT G ON G.NIP = A.NIP
LEFT JOIN TR_SKP H ON H.NIP = A.NIP AND H.TAHUN='2017'
LEFT JOIN (SELECT NIP,GRADE FROM db_absen.dbo.vwPegawai) J on A.NIP=J.NIP
WHERE A.KODE_MUTASI=1 
order by a.KODE_SATUAN_KERJA