SELECT --TOP 1000
    A.NIP_BARU, A.NAMA_LENGKAP, IIF(A.JENIS_KELAMIN=0,'Perempuan','Laki-Laki') AS JENIS_KELAMIN, A.AGAMA, A.STATUS_KAWIN, A.STATUS_PEGAWAI,
	A.JENJANG_PENDIDIKAN, A.PANGKAT, A.GOL_RUANG, A.NO_SK_GOL, A.NO_SK_JAB, A.NO_SK_GOL_KGB, G.NO_HP, G.EMAIL, H.TAHUN AS SKP2022, 
    f.LEVEL_JABATAN, A.JABATAN,  
    a.KODE_SATUAN_KERJA, e.kode_satuan_kerja as KODE_SATKER1, d.KODE_SATUAN_KERJA AS KODE_SATKER2,
	E.SATUAN_KERJA AS SATKER1, D.SATUAN_KERJA AS SATKER2, A.SATUAN_KERJA, D.PROGRAM,
    CONVERT(VARCHAR, LEFT(A.NIP_BARU,4)+'-'+RIGHT(LEFT(A.NIP_BARU,6),2)+'-'+RIGHT(LEFT(A.NIP_BARU,8),2), 23) AS TGL_LAHIR,
    CONVERT(VARCHAR, LEFT(RIGHT(A.NIP_BARU,10),4)+'-'+LEFT(RIGHT(A.NIP_BARU,6),2)+'-01', 23) AS MASUK_PEGAWAI,
    CONVERT(VARCHAR, A.TMT_PENSIUN,23) AS TMT_PENSIUN,
    CASE
        WHEN A.GOL_RUANG LIKE '%/%' THEN LEFT(A.GOL_RUANG, LEN(A.GOL_RUANG)-2)
        ELSE A.GOL_RUANG
    END AS GRUP_GOL, 
    DATEDIFF(YEAR, LEFT(A.NIP_BARU,8), GETDATE()) AS USIA, A.USIA_PENSIUN,
    CASE
        WHEN DATEDIFF(YEAR, LEFT(A.NIP_BARU,8), GETDATE()) < 24 THEN '<24'
        WHEN DATEDIFF(YEAR, LEFT(A.NIP_BARU,8), GETDATE()) BETWEEN 24 AND 29 THEN '24-29'
        WHEN DATEDIFF(YEAR, LEFT(A.NIP_BARU,8), GETDATE()) BETWEEN 30 AND 39 THEN '30-39'
        WHEN DATEDIFF(YEAR, LEFT(A.NIP_BARU,8), GETDATE()) BETWEEN 40 AND 49 THEN '40-49'
        WHEN DATEDIFF(YEAR, LEFT(A.NIP_BARU,8), GETDATE()) BETWEEN 50 AND 57 THEN '50-57'
        WHEN DATEDIFF(YEAR, LEFT(A.NIP_BARU,8), GETDATE()) > 57 THEN '>57'
    END AS GRUP_USIA,
    CASE 
        WHEN F.KODE_TIPE_JABATAN=0 THEN 'Struktural'
        WHEN F.KODE_TIPE_JABATAN=1 THEN 'Pelaksana'
        WHEN F.KODE_TIPE_JABATAN=2 THEN 'Fungsional'
        ELSE F.KODE_TIPE_JABATAN
    END AS TIPE_JABATAN, J.grade as KELAS_JAJBATAN
FROM vwDATA_PEGAWAI A 
LEFT JOIN TM_SATUAN_KERJA d ON d.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,6)+'00000000' 
LEFT JOIN TM_SATUAN_KERJA e ON e.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,4)+'0000000000'
LEFT JOIN TM_LEVEL_JABATAN f on f.KODE_LEVEL_JABATAN = a.KODE_LEVEL_JABATAN
LEFT JOIN TD_ALAMAT G ON G.NIP = A.NIP
LEFT JOIN TR_SKP H ON H.NIP = A.NIP AND H.TAHUN='2022'
LEFT JOIN (SELECT NIP,GRADE FROM db_absen.dbo.vwPegawai) J on A.NIP=J.NIP
WHERE A.KODE_MUTASI=1 
--AND A.KODE_SATUAN_KERJA LIKE '0201%'
order by a.KODE_SATUAN_KERJA