SELECT GOL_RUANG, COUNT(NIP_BARU)
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1
GROUP BY GOL_RUANG
ORDER BY GOL_RUANG

SELECT JB.KODE_TIPE_JABATAN, JB.LEVEL_JABATAN, COUNT(A.NIP_BARU) AS JUMLAH
FROM 
    TM_PEGAWAI A LEFT OUTER JOIN
    dbo.TR_JABATAN AS I ON A.NIP = I.NIP AND A.NO_URUT_JABATAN = I.NO_URUT LEFT OUTER JOIN
    dbo.TM_JABATAN AS IA ON I.KODE_JABATAN = IA.KODE_JABATAN LEFT OUTER JOIN
    dbo.TM_LEVEL_JABATAN AS JB ON IA.KODE_LEVEL_JABATAN = JB.KODE_LEVEL_JABATAN 
WHERE A.KODE_MUTASI=1
GROUP BY JB.LEVEL_JABATAN, JB.KODE_TIPE_JABATAN
ORDER BY JB.KODE_TIPE_JABATAN, JB.LEVEL_JABATAN
