SELECT STATUS_PEGAWAI, COUNT(NIP_BARU) AS JML 
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1
GROUP BY STATUS_PEGAWAI

SELECT JENIS_KELAMIN, COUNT(NIP_BARU) AS JML 
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1
GROUP BY JENIS_KELAMIN
order by JENIS_KELAMIN DESC

SELECT AGAMA, COUNT(NIP_BARU) AS JML 
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1
GROUP BY AGAMA

SELECT COUNT(NIP_BARU) AS JML 
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1

SELECT JENJANG_PENDIDIKAN, COUNT(NIP_BARU) AS JML 
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1
GROUP BY JENJANG_PENDIDIKAN 
ORDER BY JENJANG_PENDIDIKAN ASC

SELECT STATUS_KAWIN, COUNT(NIP_BARU) AS JML 
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1
GROUP BY STATUS_KAWIN

--SELECT NIP,NIP_BARU, NAMA FROM vwDATA_PEGAWAI WHERE KODE_MUTASI=1 AND STATUS_KAWIN is null IN ('-','')
