SELECT TOP 100 * FROM TS_USER WHERE ADMIN_OSS is NOT NULL
SELECT TOP 100 * FROM TS_USER WHERE TAMBAH_PEGAWAI=1

SELECT TOP 100 * FROM TEMP_PEGAWAI_SSO WHERE KODE_SATKER_3 LIKE '010211%'
SELECT * FROM TEMP_PEGAWAI_SSO WHERE NIP_USER LIKE 'non%'
SELECT TOP 100 * FROM TEMP_PEGAWAI_LATLON
SELECT TOP 100 * FROM TEMP_PEGAWAI WHERE KODE_SATKER_3 LIKE '010211%'
SELECT * FROM TEMP_PEGAWAI WHERE STATUS_PEGAWAI='' ORDER BY KODE_SATKER_4
SELECT COUNT(NIP) FROM TEMP_PEGAWAI
SELECT COUNT(USERNAME) FROM TEMP_PEGAWAI_SSO 

SELECT * FROM LOG_JABATAN
SELECT * FROM TM_JABATAN_TUKIN where JABATAN like '%pelaksana%'
SELECT * FROM TM_JABATAN 
    WHERE KODE_TINGKAT_JABATAN IS NULL
    --WHERE KODE_JABATAN='21802'
    --WHERE JABATAN LIKE 'pranata laboratorium kesehatan%'
    --WHERE KODE_JABATAN in ('20134','20126','20130','22021','20133','20125','20129','22020','20132','20124','20128','22019','20135','20127','20131','22022','21806','21805','21804')
SELECT * FROM TM_TINGKAT_JABATAN
SELECT * FROM TM_TIPE_JABATAN
SELECT * FROM TM_GRUP_JABATAN 
SELECT * FROM TM_LEVEL_JABATAN
SELECT * FROM tm_jabatan_utama 
    --WHERE JABATAN LIKE 'pranata lab%'
    WHERE KODE_JABATAN IN ('23202', '23205','23206','23207')    

SELECT * FROM TM_SATUAN_KERJA
SELECT * FROM TM_GRUP_SATUAN_KERJA

SELECT * FROM TM_KERJA
SELECT * FROM TM_KUA
SELECT * FROM TM_PEGAWAI_NON


SELECT * FROM TR_INDISIPLINER WHERE NIP='150319645'
SELECT COUNT(NIP) FROM TM_PEGAWAI WHERE KODE_MUTASI=1

SELECT * FROM TM_AGAMA
SELECT * FROM TM_STATUS_KAWIN
SELECT * FROM TM_STATUS_PEGAWAI
SELECT * FROM TM_MUTASI

SELECT * FROM vwDATA_PEGAWAI WHERE STATUS_PEGAWAI='-' AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE STATUS_KAWIN='-' AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE KODE_PANGKAT=0 AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE JENIS_KELAMIN IS NULL AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE KODE_JABATAN IS NULL AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE KODE_LEVEL_JABATAN IS NULL AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE KODE_TIPE_JABATAN IS NULL AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE GOL_RUANG='XIII' AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE GOL_RUANG='' AND KODE_MUTASI=1
SELECT * FROM vwDATA_PEGAWAI WHERE GOL_RUANG IS NULL AND KODE_MUTASI=1
SELECT top 100 * FROM vwDATA_PEGAWAI WHERE KODE_MUTASI=1

SELECT * FROM TM_PEGAWAI WHERE KODE_MUTASI=1 AND KODE_AGAMA='0'
SELECT * FROM TM_PEGAWAI WHERE KODE_MUTASI=1 AND KODE_STATUS_KAWIN='0'
SELECT * FROM TM_PEGAWAI WHERE KODE_MUTASI=1 AND KODE_STATUS_PEGAWAI=0
SELECT * FROM TM_PEGAWAI WHERE KODE_MUTASI=1 AND NO_URUT_PANGKAT IS NULL
SELECT * FROM TM_PEGAWAI WHERE KODE_MUTASI=1 AND NO_URUT_PENDIDIKAN IS NULL
SELECT * FROM TM_PEGAWAI WHERE NIP='150242192'
--UPDATE TM_PEGAWAI SET KODE_STATUS_KAWIN=1 WHERE KODE_MUTASI=1 AND NIP IN ('200901144' ,'240010872','240010874')
--UPDATE TR_JABATAN SET KODE_JABATAN='00504', kode_jabatan_utama='00504' where nip='150267029' and NO_URUT=12
--UPDATE TM_PEGAWAI SET KODE_MUTASI=88 WHERE NIP='230060000'
--UPDATE TM_PEGAWAI SET NIP_BARU='196312311990022021' WHERE NIP='150242192'

SELECT * FROM TM_JABATAN_TUKIN where JABATAN like '%pengelola data pend%'
--UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='90015'
--INSERT INTO TM_JABATAN_TUKIN (KODE_JABATAN,JABATAN,GRADE,BOBOT) SELECT KODE_JABATAN,JABATAN,6,1 FROM TM_JABATAN WHERE KODE_JABATAN='PDPE'

SELECT * FROM TM_JABATAN_TUKIN where JABATAN like '%PRANATA KOMPUTER%'
--UPDATE TM_JABATAN_TUKIN SET GRADE=6 WHERE KODE_JABATAN='22011'
--UPDATE TM_JABATAN_TUKIN SET GRADE=7 WHERE KODE_JABATAN='22013'
--UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='22014'

--check jumlah pegawai antara simpeg41 n dbstage
USE simpeg41
    SELECT COUNT(NIP) AS JUMSIMPEG FROM TM_PEGAWAI WHERE KODE_MUTASI=1;
USE dbstage
    SELECT COUNT(nip_baru) AS JMLSTAGE FROM tmPegawai;

--check pegawai baru weekly
SELECT '2020' AS TAHUN, COUNT(NIP) AS JUMLAH FROM TM_PEGAWAI WHERE YEAR(TIME_ADD)='2020'
UNION
SELECT '2021',COUNT(NIP) AS JUMLAH FROM TM_PEGAWAI WHERE YEAR(TIME_ADD)='2021'
UNION
SELECT '2022',COUNT(NIP) AS JUMLAH FROM TM_PEGAWAI WHERE YEAR(TIME_ADD)='2022'
UNION
SELECT '2023',COUNT(NIP) AS JUMLAH FROM TM_PEGAWAI WHERE YEAR(TIME_ADD)='2023'
UNION
SELECT '2024',COUNT(NIP) AS JUMLAH FROM TM_PEGAWAI WHERE YEAR(TIME_ADD)='2024'

--
SELECT COUNT(NIP) FROM TS_BACKUP_PEGAWAI

--JABATAN

SELECT * FROM tm_jabatan_utama where jabatan like 'analis klasifikasi%'
SELECT * FROM TM_JABATAN WHERE 
    --kode_jabatan LIKE 'PRG%'
    jabatan like 'analis klasifikasi%'
--INSERT INTO TM_JABATAN (KODE_JABATAN,KODE_LEVEL_JABATAN,JABATAN,TAMPIL_JABATAN,USIA_PENSIUN,TUNJANGAN,KODE_JENJANG_PENDIDIKAN,USER_ADD,TIME_ADD,USER_UPDATE,TIME_UPDATE) 
--SELECT KODE_JABATAN,KODE_LEVEL_JABATAN,JABATAN,TAMPIL_JABATAN,USIA_PENSIUN,TUNJANGAN,KODE_JENJANG_PENDIDIKAN,USER_ADD,GETDATE(),USER_ADD,GETDATE() FROM TM_JABATAN_UTAMA WHERE KODE_JABATAN='AKB1' 

SELECT GETDATE()

SELECT * from ts_user where roles=1

SELECT * FROM tm_tukin

--INSERT JABATAN PENATA RUANG KE TM_JABATAN_UTAMA
--INSERT INTO TM_JABATAN_UTAMA SELECT * FROM TM_JABATAN WHERE kode_jabatan LIKE 'PRG%'
--UPDATE TM_JABATAN_UTAMA SET KODE_LEVEL_JABATAN=102 WHERE KODE_JABATAN='PDPE'
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN=102 WHERE KODE_JABATAN='PDPE'
--UPDATE TM_JABATAN SET TUNJANGAN=185000 WHERE KODE_JABATAN='PDPE'



use dbstage
--SELECT COUNT(NIP) FROM tmPegawai
SELECT * from GRADE_PEGAWAI
SELECT * FROM tmPegawai where nip_baru='196901041990032005'
SELECT top 100 * FROM tmuser where nip='196901041990032005'

SELECT NIP, MAX(KODE_PANGKAT) / 10 AS max_data, MIN(KODE_PANGKAT) / 10 AS min_data
FROM dbo.TR_PANGKAT AS TR_PANGKAT_1
where nip='150381167'
GROUP BY NIP

SELECT * from tr_pangkat where nip='150381167'

--CEK DOUBLE TD_LAIN
SELECT NIP FROM
(
SELECT NIP, COUNT(NIP) AS JUMLAH
FROM TD_LAIN 
GROUP BY NIP
) AS LAIN WHERE JUMLAH>1

--CEK DOUBLE TD_ALAMAT
SELECT NIP FROM
(
SELECT NIP, COUNT(NIP) AS JUMLAH
FROM TD_ALAMAT 
GROUP BY NIP
) AS ALAMAT WHERE JUMLAH>1


SELECT TOP 100 * FROM TD_LAIN
SELECT TOP 100 * FROM TD_ALAMAT
SELECT TOP 100 * FROM TD_ANAK 
SELECT TOP 100 * FROM TD_PEGAWAI_LAIN 

SELECT * FROM TD_ANAK WHERE NIP='200907448'
SELECT * FROM TD_KELUARGA WHERE NIP='200907448'
SELECT * FROM TD_SUAMI_ISTRI WHERE NIP='200907448'
SELECT * FROM TD_ALAMAT WHERE NIP='230072436'
--DELETE FROM TD_ALAMAT WHERE NIP='230072436'

SELECT TOP 100 NIP, IIF(LEN(NPWP)>1,'ADA','') AS NPWP, IIF(LEN(KTP)>1,'ADA','') AS KTP  
FROM TD_LAIN

SELECT NIP, COUNT(NO_URUT) AS JML_ANAK, 
SUM(
    CAST(
        ISNULL(TERTANGGUNG,0) AS INT)) AS JML_ANAK_TG 
FROM TD_ANAK
WHERE NIP='200907448'
GROUP BY NIP

SELECT NIP, COUNT(NO_URUT) AS JML_PASANAGN, TERTANGGUNG AS PASANGAN_TTG 
FROM TD_SUAMI_ISTRI
GROUP BY NIP, TERTANGGUNG

SELECT * FROM TS_PARAMETER

SELECT * FROM TR_JABATAN WHERE NIP='240010632'
SELECT * FROM TM_PEGAWAI WHERE NIP='240010632'
SELECT * FROM TR_PANGKAT WHERE NIP='230081539'
SELECT * FROM TD_MUTASI WHERE NIP='230038194'
SELECT * FROM TD_BANK

SELECT * FROM TM_PEGAWAI

SELECT NIP, COUNT(NO_URUT) AS SERTIFIKASI 
FROM TR_SERTIFIKASI
GROUP BY NIP

SELECT TOP 100 * FROM TR_LIST
SELECT * FROM TM_JABATAN_TAMBAHAN

SELECT top 100 * FROM vwdata

--UM_USER
SELECT TOP 100 * FROM UM_USER WHERE NIP IN ('198707222019031005','198004272009011011') ORDER BY NIP
--INSERT INTO UM_USER (NIP, ROLE, APP_ID) VALUES ('198004272009011011',3,9)
--UPDATE UM_USER SET ROLE=3 WHERE ID=261


SELECT TOP 100 A.NIP_BARU, A.NAMA, B.MUTASI, S1.SATUAN_KERJA, S2.SATUAN_KERJA, S3.SATUAN_KERJA, S4.SATUAN_KERJA, S1.KODE_SATUAN_KERJA, S2.KODE_SATUAN_KERJA 
FROM 
TM_PEGAWAI A LEFT JOIN
TM_MUTASI B ON A.KODE_MUTASI=B.KODE_MUTASI LEFT JOIN 
TR_JABATAN C ON A.NIP=C.NIP AND A.NO_URUT_JABATAN=C.NO_URUT LEFT JOIN
TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,8)+'000000' 
WHERE LEN(A.NIP_BARU)>1 


SELECT * from tm_satuan_kerja
where LEFT(kode_satuan_kerja,4) in('1015','1016')

SELECT * FROM TR_SERTIFIKASI
SELECT * FROM TM_BIDANG_STUDI

SELECT * FROM TM_PANGKAT
SELECT * FROM VWDATA_PEGAWAI WHERE KODE_PANGKAT=00

SELECT * FROM TM_TINGKAT_JABATAN
SELECT * FROM TM_LEVEL_JABATAN
SELECT * FROM TM_JABATAN_UTAMA WHERE JABATAN LIKE 'PENGELOLA DATA AD%' 
SELECT * FROM TR_JABATAN WHERE KODE_JABATAN NOT IN (SELECT KODE_JABATAN FROM TM_JABATAN)
SELECT COUNT(*) FROM VWDATA_PEGAWAI WHERE KODE_MUTASI=1 AND KODE_JABATAN NOT IN (SELECT KODE_JABATAN FROM TM_JABATAN_UTAMA)
SELECT DISTINCT KODE_LEVEL_JABATAN FROM TM_JABATAN ORDER BY KODE_LEVEL_JABATAN

--INSERT INTO TM_JABATAN SELECT * FROM TM_JABATAN_UTAMA WHERE KODE_JABATAN='PDAV'

SELECT * from tm_status_pegawai