SELECT TOP 100 * FROM GRADE_PEGAWAI
SELECT TOP 100 * FROM tmPegawai_grade
SELECT TOP 100 * FROM tmJabTukin
SELECT TOP 100 * FROM tmPegawai_nonpns
SELECT TOP 100 * FROM tmPegawai WHERE grade=0
SELECT TOP 100 * FROM tmPegawai WHERE nip_baru='197707011996032001'

SELECT GRADE, COUNT(nip_baru) as JUMLAH FROM tmPegawai_grade GROUP BY grade 
SELECT GRADE, COUNT(NIP_BARU) AS JUMLAH FROM GRADE_PEGAWAI GROUP BY GRADE
SELECT GRADE, COUNT(NIP_BARU) AS JUMLAH FROM tmPegawai GROUP BY GRADE
SELECT KETERANGAN, COUNT(NIP_BARU) AS JUMLAH FROM tmPegawai WHERE grade=0 GROUP BY KETERANGAN

SELECT COUNT(NIP_BARU) FROM tmPegawai_grade
SELECT COUNT(NIP_BARU) FROM GRADE_PEGAWAI
SELECT COUNT(NIP) FROM tmPegawai_nonpns
SELECT COUNT(NIP) FROM tmPegawai

