SELECT --TOP 100 
    A.NIP_BARU, A.NAMA, B.MUTASI, B1.STATUS_PEGAWAI,
    S1.SATUAN_KERJA, S2.SATUAN_KERJA, S3.SATUAN_KERJA, S4.SATUAN_KERJA, 
    S1.KODE_SATUAN_KERJA, S2.KODE_SATUAN_KERJA 
FROM 
    TM_PEGAWAI A LEFT JOIN
    TM_MUTASI B ON A.KODE_MUTASI=B.KODE_MUTASI LEFT JOIN 
    TM_STATUS_PEGAWAI B1 ON A.KODE_STATUS_PEGAWAI=B1.KODE_STATUS_PEGAWAI LEFT JOIN
    TR_JABATAN C ON A.NIP=C.NIP AND A.NO_URUT_JABATAN=C.NO_URUT LEFT JOIN
    TM_SATUAN_KERJA AS S1 ON S1.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,2)+'000000000000' LEFT OUTER JOIN
    TM_SATUAN_KERJA AS S2 ON S2.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,4)+'0000000000' LEFT OUTER JOIN
    TM_SATUAN_KERJA AS S3 ON S3.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,6)+'00000000' LEFT OUTER JOIN
    TM_SATUAN_KERJA AS S4 ON S4.KODE_SATUAN_KERJA= LEFT(C.KODE_SATUAN_KERJA,8)+'000000' 
WHERE LEN(A.NIP_BARU)>1 
