SELECT A.*, B.KODE_UNIT_KERJA, E.SATUAN_KERJA AS SATKER1, D.SATUAN_KERJA AS SATKER2, B.NAMA FROM TM_LOG A
LEFT JOIN TS_USER B ON A.update_by = B.USERNAME
LEFT JOIN TM_SATUAN_KERJA d ON d.KODE_SATUAN_KERJA=LEFT(B.KODE_UNIT_KERJA,6)+'00000000' 
LEFT JOIN TM_SATUAN_KERJA e ON e.KODE_SATUAN_KERJA=LEFT(B.KODE_UNIT_KERJA,4)+'0000000000'
WHERE YEAR(A.log_date)='2023' AND MONTH(A.log_date)='02'
