SELECT '<24' AS JENIS, SUM(JML) AS JUMLAH FROM
    (SELECT DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE()) AS USIA, COUNT(NIP_BARU) AS JML
    FROM vwDATA_PEGAWAI
    WHERE KODE_MUTASI=1
    GROUP BY DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE())
    ) T
WHERE USIA < 24
UNION
SELECT '24-29' AS JENIS, SUM(JML) AS '24-29' FROM
    (SELECT DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE()) AS USIA, COUNT(NIP_BARU) AS JML
    FROM vwDATA_PEGAWAI
    WHERE KODE_MUTASI=1
    GROUP BY DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE())
    ) T
WHERE USIA BETWEEN 24 AND 29
UNION
SELECT '30-39' AS JENIS, SUM(JML) AS '30-39' FROM
    (SELECT DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE()) AS USIA, COUNT(NIP_BARU) AS JML
    FROM vwDATA_PEGAWAI
    WHERE KODE_MUTASI=1
    GROUP BY DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE())
    ) T
WHERE USIA BETWEEN 30 AND 39
UNION
SELECT '40-49' AS JENIS, SUM(JML) AS '40-49' FROM
    (SELECT DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE()) AS USIA, COUNT(NIP_BARU) AS JML
    FROM vwDATA_PEGAWAI
    WHERE KODE_MUTASI=1
    GROUP BY DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE())
    ) T
WHERE USIA BETWEEN 40 AND 49
UNION
SELECT '50-57' AS JENIS, SUM(JML) AS '50-57' FROM
    (SELECT DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE()) AS USIA, COUNT(NIP_BARU) AS JML
    FROM vwDATA_PEGAWAI
    WHERE KODE_MUTASI=1
    GROUP BY DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE())
    ) T
WHERE USIA BETWEEN 50 AND 57
UNION
SELECT '>57' AS JENIS, SUM(JML) AS '>57' FROM
    (SELECT DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE()) AS USIA, COUNT(NIP_BARU) AS JML
    FROM vwDATA_PEGAWAI
    WHERE KODE_MUTASI=1
    GROUP BY DATEDIFF(YEAR, LEFT(NIP_BARU,8), GETDATE())
    ) T
WHERE USIA > 57 