SELECT A.KODE_BIDANG_STUDI, B.JENIS_BIDANG_STUDI, BIDANG_STUDI from TM_BIDANG_STUDI A
LEFT JOIN TM_JENIS_BIDANG_STUDI B ON A.KODE_JENIS_BIDANG_STUDI=B.KODE_JENIS_BIDANG_STUDI
ORDER BY B.KODE_JENIS_BIDANG_STUDI