SELECT COUNT(NAMA) AS JML_PEG_BARU FROM TM_PEGAWAI WHERE YEAR(TIME_ADD)='2024' AND MONTH(TIME_ADD)='02'

SELECT COUNT(NIP_BARU) AS JML_PENSIUN FROM vwDATA_PEGAWAI WHERE YEAR(TMT_PENSIUN)='2023' AND MONTH(TMT_PENSIUN)='02'

SELECT TOP 100 * FROM vwDATA_PEGAWAI

SELECT NIP_BARU, NAMA, RIGHT(LEFT(NIP_BARU,12),4) AS TMT, USER_ADD
FROM TM_PEGAWAI 
WHERE YEAR(TIME_ADD)='2024' 

SELECT * FROM TM_PEGAWAI WHERE NIP='240010593'