SELECT ROW_NUMBER() OVER(ORDER BY KODE_SATUAN_KERJA ASC) AS URUT, NIP_BARU, NAMA, TIPE_JABATAN, JABATAN, PANGKAT, GOL_RUANG, CAST(TMT_SK AS DATE) TMT_KP, SATKER1, SATKER2, NO_HP, KODE_SATUAN_KERJA FROM
(SELECT A.NIP, A.NIP_BARU, A.NAMA, D.KODE_TIPE_JABATAN, D1.TIPE_JABATAN, C.JABATAN, 
	B.KODE_SATUAN_KERJA, I.SATUAN_KERJA AS SATKER1, J.SATUAN_KERJA AS SATKER2,
	E.KODE_JENJANG_PENDIDIKAN, F.JENJANG_PENDIDIKAN, 
	G.KODE_PANGKAT, H.PANGKAT, H.GOL_RUANG, G.TMT_SK, K.NO_HP,
	CASE 
	WHEN D1.KODE_TIPE_JABATAN = '1' THEN (SELECT CASE
        WHEN (F.KODE_JENJANG_PENDIDIKAN = '0' AND G.KODE_PANGKAT = '21') THEN 1 
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '1' AND G.KODE_PANGKAT = '23') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '2' AND G.KODE_PANGKAT = '32') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '3' AND G.KODE_PANGKAT = '32') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '4' AND G.KODE_PANGKAT = '32') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '5' AND G.KODE_PANGKAT = '33') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '6' AND G.KODE_PANGKAT = '34') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '7' AND G.KODE_PANGKAT = '34') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '8' AND G.KODE_PANGKAT = '41') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '9' AND G.KODE_PANGKAT = '42') THEN 1
		WHEN (F.KODE_JENJANG_PENDIDIKAN = '10' AND G.KODE_PANGKAT = '33') THEN 1
		ELSE 0 END)
	WHEN D.KODE_TIPE_JABATAN = '0' THEN (SELECT CASE 
		WHEN (D.KODE_LEVEL_JABATAN = '001' AND G.KODE_PANGKAT = '45') THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '002' AND G.KODE_PANGKAT = '45') THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '003' AND G.KODE_PANGKAT = '44') THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '004' AND G.KODE_PANGKAT = '43') THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '005' AND G.KODE_PANGKAT = '42') THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '006' AND G.KODE_PANGKAT = '41') THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '007' AND G.KODE_PANGKAT = '34') THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '008' AND G.KODE_PANGKAT = '33' AND CAST(F.KODE_JENJANG_PENDIDIKAN AS INT) <= 5) THEN 1
		WHEN (D.KODE_LEVEL_JABATAN = '009' AND G.KODE_PANGKAT = '32' AND CAST(F.KODE_JENJANG_PENDIDIKAN AS INT) < 5) THEN 1
		ELSE 0 END)
	END AS ISPUNCAK
FROM 
	TM_PEGAWAI A LEFT JOIN 
	TR_JABATAN B ON A.NIP = B.NIP AND A.NO_URUT_JABATAN = B.NO_URUT LEFT JOIN
	TM_JABATAN C ON B.KODE_JABATAN = C.KODE_JABATAN LEFT JOIN
	TM_LEVEL_JABATAN D ON C.KODE_LEVEL_JABATAN = D.KODE_LEVEL_JABATAN LEFT JOIN
	TM_TIPE_JABATAN D1 ON D.KODE_TIPE_JABATAN = D1.KODE_TIPE_JABATAN LEFT JOIN
	TR_PENDIDIKAN E ON A.NIP = E.NIP AND A.NO_URUT_PENDIDIKAN = E.NO_URUT LEFT JOIN
	TM_JENJANG_PENDIDIKAN F ON E.KODE_JENJANG_PENDIDIKAN = F.KODE_JENJANG_PENDIDIKAN LEFT JOIN
	TR_PANGKAT G ON A.NIP = G.NIP AND A.NO_URUT_PANGKAT = G.NO_URUT LEFT JOIN
	TM_PANGKAT H ON G.KODE_PANGKAT = H.KODE_PANGKAT LEFT JOIN 
	TM_SATUAN_KERJA I ON LEFT(B.KODE_SATUAN_KERJA,6)+'00000000' = I.KODE_SATUAN_KERJA LEFT JOIN
	TM_SATUAN_KERJA J ON LEFT(B.KODE_SATUAN_KERJA,4)+'0000000000' = J.KODE_SATUAN_KERJA LEFT JOIN
	TD_ALAMAT K ON A.NIP = K.NIP
WHERE 
	A.KODE_MUTASI = '1' AND 
	(YEAR(CAST( GETDATE() AS Date )) - YEAR(G.TMT_SK) >= 4) AND 
	G.TMT_SK <> CAST('04/01/2018' AS DATE) AND
	D.KODE_TIPE_JABATAN IN ('0','1')
) AS KPO WHERE ISPUNCAK = 0 ORDER BY KODE_SATUAN_KERJA ASC