SELECT B.MUTASI, COUNT(A.NIP) FROM TM_PEGAWAI A
LEFT JOIN TM_MUTASI B ON A.KODE_MUTASI = B.KODE_MUTASI
WHERE YEAR(A.TIME_UPDATE)=2023 AND MONTH(A.TIME_UPDATE)=10 AND DAY(A.TIME_UPDATE)=18 AND A.KODE_MUTASI<>1
GROUP BY B.MUTASI