SELECT * FROM 
(
	SELECT A.KODE_JENJANG_PENDIDIKAN, A.JENJANG_PENDIDIKAN, A.GOL_RUANG, COUNT(A.NIP_BARU) AS JUMLAH 
	FROM vwDATA_PEGAWAI A 
	WHERE A.KODE_MUTASI ='1' 
	GROUP BY A.KODE_JENJANG_PENDIDIKAN, A.JENJANG_PENDIDIKAN, A.GOL_RUANG
) t
PIVOT
(
	SUM(JUMLAH) FOR GOL_RUANG IN ([LAIN-LAIN],[I/a],[I/b],[I/c],[I/d],[II/a],[II/b],[II/c],[II/d],[III/a],[III/b],[III/c],[III/d],
    [IV/a],[IV/b],[IV/c],[IV/d],[IV/e],[I],[II],[III],[IV],[V],[VI],[VII],[VIII],[IX],[X],[XI],[XII],[XIII],[XIV],[XV],[XVI],[XVII])
) piv
ORDER BY KODE_JENJANG_PENDIDIKAN

--select top 10 * from vwDATA_PEGAWAI where kode_mutasi=1
--SELECT * FROM TM_PANGKAT