
SELECT A.KODE_SATUAN_KERJA, B.SATUAN_KERJA, A.JUMLAH, A.SK_GOL, A.SK_JAB, A.SK_KGB, A.NO_HP, A.EMAIL, A.SKP2021 
FROM
(SELECT 
    LEFT(A.KODE_SATUAN_KERJA,4)+'0000000000' AS KODE_SATUAN_KERJA, COUNT(A.NIP_BARU) AS JUMLAH,
    COUNT(A.NO_SK_GOL) AS SK_GOL, COUNT(A.NO_SK_JAB) AS SK_JAB, COUNT(NO_SK_GOL_KGB) AS SK_KGB,
    COUNT(G.NO_HP) AS NO_HP , COUNT(G.EMAIL) AS EMAIL, COUNT(H.TAHUN) AS SKP2021
FROM vwDATA_PEGAWAI A 
LEFT JOIN TD_ALAMAT G ON G.NIP = A.NIP
LEFT JOIN TR_SKP H ON H.NIP = A.NIP AND H.TAHUN='2021'
WHERE KODE_MUTASI=1 
AND (NO_SK_GOL<>'' OR NO_SK_GOL IS NOT NULL OR NO_SK_JAB<>'' OR NO_SK_JAB IS NOT NULL OR NO_SK_GOL_KGB<>'' OR NO_SK_GOL_KGB IS NOT NULL OR NO_HP<>'' OR NO_HP IS NOT NULL OR EMAIL<>'' OR EMAIL IS NOT NULL OR H.TAHUN<>'' OR H.TAHUN IS NOT NULL) 
--AND A.KODE_SATUAN_KERJA LIKE '0102%'
GROUP BY LEFT(A.KODE_SATUAN_KERJA,4)) A
LEFT JOIN
TM_SATUAN_KERJA B ON A.KODE_SATUAN_KERJA=B.KODE_SATUAN_KERJA
ORDER BY A.KODE_SATUAN_KERJA 
