--SELECT KODE_LEVEL_JABATAN, LEVEL_JABATAN FROM TM_LEVEL_JABATAN

SELECT KODE_LEVEL_JABATAN, COUNT(NIP_BARU) FROM vwDATA_PEGAWAI WHERE KODE_MUTASI=1 GROUP BY KODE_LEVEL_JABATAN ORDER BY KODE_LEVEL_JABATAN

