SELECT --TOP 100
    A.NIP_BARU, A.NAMA_LENGKAP, A.STATUS_PEGAWAI, 
    A.PANGKAT, A.GOL_RUANG,CONVERT(VARCHAR, A.TMT_SK_GOL,23) AS TMT_SK_GOL, A.MK_TAHUN, A.MK_BULAN,
	A.JABATAN, f.LEVEL_JABATAN, 
    CASE 
        WHEN F.KODE_TIPE_JABATAN=0 THEN 'Struktural'
        WHEN F.KODE_TIPE_JABATAN=1 THEN 'Pelaksana'
        WHEN F.KODE_TIPE_JABATAN=2 THEN 'Fungsional'
        ELSE F.KODE_TIPE_JABATAN
    END AS TIPE_JABATAN,
    J.grade as KELAS_JABATAN,
    CONVERT(VARCHAR, A.TMT_SK_JAB,23) AS TMT_JAB, 
    A.USIA_PENSIUN, CONVERT(VARCHAR, A.TMT_PENSIUN,23) AS TMT_PENSIUN, 
    A.KODE_SATUAN_KERJA, E.SATUAN_KERJA AS SATKER1, D.SATUAN_KERJA AS SATKER2, A.SATUAN_KERJA, D.PROGRAM 
FROM vwDATA_PEGAWAI A 
LEFT JOIN TM_SATUAN_KERJA d ON d.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,6)+'00000000' 
LEFT JOIN TM_SATUAN_KERJA e ON e.KODE_SATUAN_KERJA=LEFT(a.KODE_SATUAN_KERJA,4)+'0000000000'
LEFT JOIN TM_LEVEL_JABATAN f on f.KODE_LEVEL_JABATAN = a.KODE_LEVEL_JABATAN
LEFT JOIN TD_ALAMAT G ON G.NIP = A.NIP
LEFT JOIN TR_SKP H ON H.NIP = A.NIP AND H.TAHUN='2021'
LEFT JOIN (SELECT NIP,GRADE FROM db_absen.dbo.vwPegawai) J on A.NIP=J.NIP
WHERE A.KODE_MUTASI=1 
order by a.KODE_SATUAN_KERJA