SELECT --TOP 100
    L.KTP, CONCAT(A.GDN1, A.GDN2) AS GELAR_DEPAN, REPLACE(A.NAMA,',','') AS NAMA_LENGKAP, A.GBN, 
    CONCAT(REPLACE(A.TEMPAT_LAHIR,',',''), ', ', CONVERT(VARCHAR, A.TANGGAL_LAHIR,23)) AS TEMPAT_TANGGAL_LAHIR, 
    IIF(A.JENIS_KELAMIN=0,'Perempuan','Laki-Laki') AS JENIS_KELAMIN, A.NIP_BARU, 
	A.KETERANGAN_SATUAN_KERJA, A.JABATAN, G.EMAIL, G.NO_HP, A.KODE_SATUAN_KERJA
FROM vwDATA_PEGAWAI A 
LEFT JOIN TD_ALAMAT G ON G.NIP = A.NIP
LEFT JOIN TD_LAIN L ON L.NIP = A.NIP
WHERE A.KODE_MUTASI=1 
    AND A.KODE_SATUAN_KERJA LIKE '010211%'
order by a.KODE_SATUAN_KERJA


