SELECT NIP
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1 AND STATUS_PEGAWAI='CPNS' 

SELECT NIP FROM TR_PANGKAT
WHERE NIP IN  (SELECT NIP
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1 AND STATUS_PEGAWAI='CPNS')
AND JENIS_SK='JP002'

SELECT * FROM TM_PANGKAT
SELECT * FROM TM_REF

/*
UPDATE TM_PEGAWAI SET KODE_STATUS_PEGAWAI=1 
WHERE NIP IN (SELECT NIP FROM TR_PANGKAT
WHERE NIP IN  (SELECT NIP
FROM vwDATA_PEGAWAI
WHERE KODE_MUTASI=1 AND STATUS_PEGAWAI='CPNS')
AND JENIS_SK='JP002')
*/

SELECT * FROM TM_STATUS_PEGAWAI