select NO_URUT, KODE_JABATAN, kode_jabatan_utama, kode_jabatan_tambahan  from tr_jabatan where nip='230030764'

SELECT * from tm_pegawai where nip='230030764'

SELECT * from tm_jabatan_utama where KODE_LEVEL_JABATAN='222'
SELECT * from TM_LEVEL_JABATAN
SELECT * from tm_jabatan where JABATAN like 'BIDAN%'
SELECT * from tm_jabatan_tambahan

--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='BDN' WHERE KODE_JABATAN='20954';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='BDN' WHERE KODE_JABATAN='20956';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='BDN' WHERE KODE_JABATAN='20957';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='BDN' WHERE KODE_JABATAN='20958';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='BDN' WHERE KODE_JABATAN='20959';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='BDN' WHERE KODE_JABATAN='20960';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='BDN' WHERE KODE_JABATAN='90013';

--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='DRG' WHERE KODE_JABATAN='20325';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='DRG' WHERE KODE_JABATAN='90014';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='DRG' WHERE KODE_JABATAN='90024';
--UPDATE TM_JABATAN SET KODE_LEVEL_JABATAN='DRG' WHERE KODE_JABATAN='90026';
