SELECT * FROM TM_JABATAN_TUKIN where JABATAN like '%perawat%'
--UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='90015'

SELECT * FROM TM_JABATAN_TUKIN where JABATAN like '%PRANATA KOMPUTER%'
--UPDATE TM_JABATAN_TUKIN SET GRADE=6 WHERE KODE_JABATAN='22011'
--UPDATE TM_JABATAN_TUKIN SET GRADE=7 WHERE KODE_JABATAN='22013'
--UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='22014'

/* --update 20240110-0914
UPDATE TM_JABATAN_TUKIN SET GRADE=6 WHERE KODE_JABATAN='20914';
UPDATE TM_JABATAN_TUKIN SET GRADE=7 WHERE KODE_JABATAN='20916';
UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='20917';
UPDATE TM_JABATAN_TUKIN SET GRADE=6 WHERE KODE_JABATAN='22001';
UPDATE TM_JABATAN_TUKIN SET GRADE=7 WHERE KODE_JABATAN='22005';
UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='22004';
UPDATE TM_JABATAN_TUKIN SET GRADE=6 WHERE KODE_JABATAN='20501';
UPDATE TM_JABATAN_TUKIN SET GRADE=7 WHERE KODE_JABATAN='90011';
UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='90012';
UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='ASD1';
UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='PBY04';
UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='PFM';
UPDATE TM_JABATAN_TUKIN SET GRADE=10 WHERE KODE_JABATAN='PFM12';
UPDATE TM_JABATAN_TUKIN SET GRADE=10 WHERE KODE_JABATAN='PFM2';
UPDATE TM_JABATAN_TUKIN SET GRADE=10 WHERE KODE_JABATAN='20326';
UPDATE TM_JABATAN_TUKIN SET GRADE=9 WHERE KODE_JABATAN='90027';
UPDATE TM_JABATAN_TUKIN SET GRADE=9 WHERE KODE_JABATAN='90024';
UPDATE TM_JABATAN_TUKIN SET GRADE=6 WHERE KODE_JABATAN='90013';
UPDATE TM_JABATAN_TUKIN SET GRADE=7 WHERE KODE_JABATAN='20956';
UPDATE TM_JABATAN_TUKIN SET GRADE=8 WHERE KODE_JABATAN='20957';
UPDATE TM_JABATAN_TUKIN SET GRADE=6 WHERE KODE_JABATAN='22025';
UPDATE TM_JABATAN_TUKIN SET GRADE=7 WHERE KODE_JABATAN='22026';
*/


